CREATE TABLE  "FIN_CARRERA" 
   (	"ID_PILOTO" NUMBER NOT NULL ENABLE, 
	"FECHA_FIN_CARRERA" TIMESTAMP (6) NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "INICIO_CARRERA" 
   (	"ID_COMPETIDOR" NUMBER NOT NULL ENABLE, 
	"PILOTO" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"EQUIPO" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INICIO_CARRERA" TIMESTAMP (6) NOT NULL ENABLE, 
	"CATEGORIA" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "INICIO_CARRERA_PK" PRIMARY KEY ("ID_COMPETIDOR")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INICIO_CARRERA_CON" UNIQUE ("PILOTO", "EQUIPO")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE UNIQUE INDEX  "INICIO_CARRERA_CON" ON  "INICIO_CARRERA" ("PILOTO", "EQUIPO")
/
CREATE UNIQUE INDEX  "INICIO_CARRERA_PK" ON  "INICIO_CARRERA" ("ID_COMPETIDOR")
/
 CREATE SEQUENCE   "INICIO_CARRERA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 66 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_INICIO_CARRERA" 
  before insert on "INICIO_CARRERA"               
  for each row  
begin   
  if :NEW."ID_COMPETIDOR" is null then 
    select "INICIO_CARRERA_SEQ".nextval into :NEW."ID_COMPETIDOR" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_INICIO_CARRERA" ENABLE
/
